###################################### Single Broker

version: '3.7'

services:
  # https://hub.docker.com/r/confluentinc/cp-zookeeper/tags
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  # https://hub.docker.com/r/confluentinc/cp-kafka/tags
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
  # https://hub.docker.com/r/obsidiandynamics/kafdrop
  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:19092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    depends_on:
      - kafka


###################################### Multiple Brokers


#---
#version: '2'
#services:
#  zookeeper-1:
#    image: confluentinc/cp-zookeeper:latest
#    environment:
#      ZOOKEEPER_SERVER_ID: 1
#      ZOOKEEPER_CLIENT_PORT: 22181
#      ZOOKEEPER_TICK_TIME: 2000
#      ZOOKEEPER_INIT_LIMIT: 5
#      ZOOKEEPER_SYNC_LIMIT: 2
#      ZOOKEEPER_SERVERS: localhost:22888:23888;localhost:32888:33888;localhost:42888:43888
#    network_mode: host
#    extra_hosts:
#      - "moby:127.0.0.1"
#
#  zookeeper-2:
#    image: confluentinc/cp-zookeeper:latest
#    environment:
#      ZOOKEEPER_SERVER_ID: 2
#      ZOOKEEPER_CLIENT_PORT: 32181
#      ZOOKEEPER_TICK_TIME: 2000
#      ZOOKEEPER_INIT_LIMIT: 5
#      ZOOKEEPER_SYNC_LIMIT: 2
#      ZOOKEEPER_SERVERS: localhost:22888:23888;localhost:32888:33888;localhost:42888:43888
#    network_mode: host
#    extra_hosts:
#      - "moby:127.0.0.1"
#
#  zookeeper-3:
#    image: confluentinc/cp-zookeeper:latest
#    environment:
#      ZOOKEEPER_SERVER_ID: 3
#      ZOOKEEPER_CLIENT_PORT: 42181
#      ZOOKEEPER_TICK_TIME: 2000
#      ZOOKEEPER_INIT_LIMIT: 5
#      ZOOKEEPER_SYNC_LIMIT: 2
#      ZOOKEEPER_SERVERS: localhost:22888:23888;localhost:32888:33888;localhost:42888:43888
#    network_mode: host
#    extra_hosts:
#      - "moby:127.0.0.1"
#
#  kafka-1:
#    image: confluentinc/cp-kafka:latest
#    network_mode: host
#    depends_on:
#      - zookeeper-1
#      - zookeeper-2
#      - zookeeper-3
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_ZOOKEEPER_CONNECT: localhost:22181,localhost:32181,localhost:42181
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:19092
#    extra_hosts:
#      - "moby:127.0.0.1"
#
#  kafka-2:
#    image: confluentinc/cp-kafka:latest
#    network_mode: host
#    depends_on:
#      - zookeeper-1
#      - zookeeper-2
#      - zookeeper-3
#    environment:
#      KAFKA_BROKER_ID: 2
#      KAFKA_ZOOKEEPER_CONNECT: localhost:22181,localhost:32181,localhost:42181
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092
#    extra_hosts:
#      - "moby:127.0.0.1"
#
#  kafka-3:
#    image: confluentinc/cp-kafka:latest
#    network_mode: host
#    depends_on:
#      - zookeeper-1
#      - zookeeper-2
#      - zookeeper-3
#    environment:
#      KAFKA_BROKER_ID: 3
#      KAFKA_ZOOKEEPER_CONNECT: localhost:22181,localhost:32181,localhost:42181
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:39092
#    extra_hosts:
#      - "moby:127.0.0.1"